#!/bin/zsh

#export GIT_AUTHOR_NAME="${FULLNAME}"
#export GIT_AUTHOR_EMAIL="${EMAIL}"
#export GIT_COMMITTER_NAME="${FULLNAME}"
#export GIT_COMMITTER_EMAIL="${EMAIL}"

#----------

git_init () {
  git init \
  && git add . \
  && git commit -m "initial commit" \
  && git gc
}

alias = gin=git_init
