#!/bin/zsh

#export GIT_AUTHOR_NAME="${FULLNAME}"
#export GIT_AUTHOR_EMAIL="${EMAIL}"
#export GIT_COMMITTER_NAME="${FULLNAME}"
#export GIT_COMMITTER_EMAIL="${EMAIL}"

#----------

ginit {
  git init \
  && git add . \
  && git commit -m "initial commit" \
  && git gc
}
