#!/usr/bin/zsh

reload() {
  if [[ "$#*" -eq 0 ]]; then
    [[ -r ~/.zshrc ]] && . ~/.zshrc
  else
    local function
    for function in "$@"; do
      ufunction $function
      autoload -U $function
    done
  fi
}
